cleaning-settings:
  all:
    states: [AK, AL, AR, AZ, CA, CO, CT, FL, GA, HI, IA, IL, IN, KS, KY, LA, MA, MN, MS, NC, NJ, NV, OR, PA, WA, WI, VA]
    run: TRUE
  partial:
    states: []
    run: FALSE
