cleaning-settings:
  all:
    states: [AK, AL, AR, AZ, CA, CO, CT, FL, GA, HI, IA, IL, IN, KS, KY, LA, MA, MD, MN, MS, NM, NC, NJ, NV, TN, OR, PA, SC, WA, WI, VA]
    run: TRUE
  partial:
    states: []
    run: FALSE
